version: "3"
services:
    nginx:
        container_name: nginx_container
        image: nginx:latest
        restart: always
        networks:
            - nginx-net
        ports:
            - 9999:80
        volumes:
            - ./volume/nginx/data:/html
networks:
    nginx-net:
        driver: bridge
