version: "3"
services:
    nginx:
        container_name: nginx_container
        image: nginx:latest
        restart: always
        network_mode: host
        ports:
            - 7070:7070
            - 9090:8080
        volumes:
            - ./volume/nginx/data:/html
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./index.html:/etc/nginx/src/index.html
